# Generated by Django 4.0.4 on 2022-05-25 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='books',
        ),
        migrations.AddField(
            model_name='invoice',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.book', verbose_name='Book'),
        ),
        migrations.DeleteModel(
            name='relation',
        ),
    ]
