# Generated by Django 4.0.4 on 2022-05-25 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_invoice_books_invoice_book_delete_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.book', verbose_name='Book'),
        ),
    ]
