# Generated by Django 4.0.4 on 2022-05-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_invoice_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='salesman',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
    ]
